language: python
dist: xenial
cache: pip
python:
  - 3.7

install:
  - pip install tqdm
  - pip install docutils
  - pip install -e .
#   - pip install black>=19.10b0

if pull_request = false

env: MPLBACKEND=Agg

jobs:
  allow_failures:
    env:
      - CAN_FAIL=true
  include:
    - stage: "linting"
      env: CAN_FAIL=true
#       script: black --check .
    - stage: "test"
      script:
        - pytest
#         - rst2html.py --halt=2 README.rst >/dev/null
#- rst2html.py --strict README.rst >/dev/null

after_success:
  - codecov
  - pip list

branches:
  only:
  - master

notifications:
  email: false
